variables:
  UNIVERSITY: $UNIVERSITY

stages:
  - build
  - deploy_pprd
  - deploy_prod

build:
  stage: build
  image: node:lts
  before_script:
    - echo "@vue-unistra:registry=https://gitlab.unistra.fr/api/v4/packages/npm/" >> .npmrc
    - echo "//git.unistra.fr/api/v4/projects/9346/packages/npm/:_authToken=$CI_JOB_TOKEN" >> .npmrc
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

deploy_pprd:
  stage: deploy_pprd
  image: alpine
  before_script:
    - apk add rclone
    - rclone config create unistra s3 provider Ceph endpoint https://s3.unistra.fr acl public-read access_key_id $S3_ACCESSKEYID secret_access_key $S3_SECRETACCESSKEY
  script:
    - rclone sync dist/* unistra:plana-"$UNIVERSITY"-preprod/front-static
  only:
    - main

deploy_prod:
  stage: deploy_prod
  image: alpine
  before_script:
    - apk add rclone
    - rclone config create unistra s3 provider Ceph endpoint https://s3.unistra.fr acl public-read access_key_id $S3_ACCESSKEYID secret_access_key $S3_SECRETACCESSKEY
  script:
    - rclone sync dist/* unistra:plana-"$UNIVERSITY"-prod/front-static
  only:
    - tags
    - main