# You need to set this variable!
# Unistra does not use this CI for deployment
variables:
  UNIVERSITY: "unistra"

stages:
  - test
  - deploy_saas

type_check:
  stage: test
  image: node:lts
  tags:
    - cluster
  only:
    - develop
  script:
    - npm install --progress=false
    - npm run lint
    - npm run typecheck

unit_test:
  stage: test
  image: node:lts
  tags:
    - cluster
  only:
    - develop
  script:
    - npm install --progress=false
    - npm run test:unit:coverage
  coverage: /All files\s*\|\s*([\d\.]+)/

deploy_saas:
  stage: deploy_saas
  rules:
    - if: $UNIVERSITY != "unistra"
  trigger:
    include: .deploy-saas.gitlab-ci.yml
  variables:
    UNIVERSITY: $UNIVERSITY