# You need to set these variables!
# Unistra does not use this CI for deployment
variables:
  UNIVERSITY: "unistra"
  CUSTOM_REPO: "git_repo"

stages:
  - test
  - deploy_saas

type_check:
  stage: test
  image: node:lts
  tags:
    - cluster
  only:
    - develop
  script:
    - npm install --progress=false
    - npm run lint
    - npm run typecheck

unit_test:
  stage: test
  image: node:lts
  tags:
    - cluster
  only:
    - develop
  script:
    - npm install --progress=false
    - npm run test:unit:coverage
  coverage: /All files\s*\|\s*([\d\.]+)/

deploy_saas_preprod:
  stage: deploy_saas
  trigger:
    include:
      - local: .deploy-saas.gitlab-ci.yml
  rules:
    - if: $UNIVERSITY != "unistra" && $CI_COMMIT_BRANCH == "main"
  variables:
    UNIVERSITY: $UNIVERSITY
    CUSTOM_REPO: $CUSTOM_REPO
    DEPLOY_ENV: "preprod"

deploy_saas_prod:
  stage: deploy_saas
  trigger:
    include:
      - local: .deploy-saas.gitlab-ci.yml
  rules:
    - if: $UNIVERSITY != "unistra" && $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG
  variables:
    UNIVERSITY: $UNIVERSITY
    CUSTOM_REPO: $CUSTOM_REPO
    DEPLOY_ENV: "prod"